### ISSUE TITLE
Make fails. 'macro "access_ok" passed 3 arguments, but takes just 2'

### ISSUE THREAD

**Issue by Magicrafter13** [pkeeper/rt3290sta#3]
Attempt to compile on Ubuntu 19.10
```
make -C tools
make[1]: Entering directory '/home/matthew/Documents/rt3290sta/tools'
gcc -g bin2h.c -o bin2h
make[1]: Leaving directory '/home/matthew/Documents/rt3290sta/tools'
/home/matthew/Documents/rt3290sta/tools/bin2h
cp -f os/linux/Makefile.6 /home/matthew/Documents/rt3290sta/os/linux/Makefile
make -C /lib/modules/5.3.0-23-generic/build SUBDIRS=/home/matthew/Documents/rt3290sta/os/linux modules
make[1]: Entering directory '/usr/src/linux-headers-5.3.0-23-generic'
Makefile:227: ================= WARNING ================
Makefile:228: 'SUBDIRS' will be removed after Linux 5.3
Makefile:229:
Makefile:230: If you are building an individual subdirectory
Makefile:231: in the kernel tree, you can do like this:
Makefile:232: $ make path/to/dir/you/want/to/build/
Makefile:233: (Do not forget the trailing slash)
Makefile:234:
Makefile:235: If you are building an external module,
Makefile:236: Please use 'M=' or 'KBUILD_EXTMOD' instead
Makefile:237: ==========================================
  CC [M]  /home/matthew/Documents/rt3290sta/os/linux/../../os/linux/sta_ioctl.o
/home/matthew/Documents/rt3290sta/os/linux/../../os/linux/sta_ioctl.c: In function 'rt28xx_sta_ioctl':
/home/matthew/Documents/rt3290sta/os/linux/../../os/linux/sta_ioctl.c:2587:72: error: macro "access_ok" passed 3 arguments, but takes just 2
 2587 |     if ( access_ok(VERIFY_WRITE, wrqin->u.data.pointer, sizeof(privtab)) != TRUE)
      |                                                                        ^
In file included from ./include/linux/uaccess.h:11,
                 from ./arch/x86/include/asm/fpu/xstate.h:5,
                 from ./arch/x86/include/asm/pgtable.h:26,
                 from ./include/linux/mm.h:99,
                 from ./include/linux/scatterlist.h:8,
                 from ./include/linux/dmapool.h:14,
                 from ./include/linux/pci.h:1429,
                 from /home/matthew/Documents/rt3290sta/include/os/rt_linux.h:28,
                 from /home/matthew/Documents/rt3290sta/include/rtmp_os.h:42,
                 from /home/matthew/Documents/rt3290sta/include/rtmp_comm.h:56,
                 from /home/matthew/Documents/rt3290sta/os/linux/../../os/linux/sta_ioctl.c:33:
./arch/x86/include/asm/uaccess.h:93: note: macro "access_ok" defined here
   93 | #define access_ok(addr, size)     \
      |
/home/matthew/Documents/rt3290sta/os/linux/../../os/linux/sta_ioctl.c:2587:10: error: 'access_ok' undeclared (first use in this function)
 2587 |     if ( access_ok(VERIFY_WRITE, wrqin->u.data.pointer, sizeof(privtab)) != TRUE)
      |          ^~~~~~~~~
/home/matthew/Documents/rt3290sta/os/linux/../../os/linux/sta_ioctl.c:2587:10: note: each undeclared identifier is reported only once for each function it appears in
/home/matthew/Documents/rt3290sta/os/linux/../../os/linux/sta_ioctl.c:2600:73: error: macro "access_ok" passed 3 arguments, but takes just 2
 2600 |    if(access_ok(VERIFY_READ, wrqin->u.data.pointer, wrqin->u.data.length) != TRUE)
      |                                                                         ^
In file included from ./include/linux/uaccess.h:11,
                 from ./arch/x86/include/asm/fpu/xstate.h:5,
                 from ./arch/x86/include/asm/pgtable.h:26,
                 from ./include/linux/mm.h:99,
                 from ./include/linux/scatterlist.h:8,
                 from ./include/linux/dmapool.h:14,
                 from ./include/linux/pci.h:1429,
                 from /home/matthew/Documents/rt3290sta/include/os/rt_linux.h:28,
                 from /home/matthew/Documents/rt3290sta/include/rtmp_os.h:42,
                 from /home/matthew/Documents/rt3290sta/include/rtmp_comm.h:56,
                 from /home/matthew/Documents/rt3290sta/os/linux/../../os/linux/sta_ioctl.c:33:
./arch/x86/include/asm/uaccess.h:93: note: macro "access_ok" defined here
   93 | #define access_ok(addr, size)     \
      |
make[2]: *** [scripts/Makefile.build:290: /home/matthew/Documents/rt3290sta/os/linux/../../os/linux/sta_ioctl.o] Error 1
make[1]: *** [Makefile:1655: _module_/home/matthew/Documents/rt3290sta/os/linux] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.3.0-23-generic'
make: *** [Makefile:389: LINUX] Error 2
```

**Comment by pkeeper** [comment]
Hello. 
Sorry I'm not mantaining this repo, I'll close it soon.
This is a fork that I've made that I've adapted to my system at the time, it's not compatible with other environments, and even in my build it was unstable and while faster and had stronger link than kernel's driver it sometimes just hung and needed a driver reload.
I'm not proficient enough in C to debug it and have no time to struggle with it, so I've just bought an external WI-FI\Bluetooth that I use when I need more signal strength or speed.
Good luck!
